/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.fuseanalytics.gradle.x509

import org.gradle.api.Project
import org.gradle.api.Plugin

import java.security.KeyStore

class SslCertGenPlugin implements Plugin<Project> {

    void apply(Project project) {
        project.extensions.add(CertificateExtension, "certificate", new CertificateExtension() )
        File certFile = project.file("${project.buildDir}/certificate/${project.name.toLowerCase().replaceAll(/\s/, "_")}.pkcs12")

        project.tasks.register("generateCert") {
            description = "Generates a self-signed X509 Certificate according to the configuration."
            group = "certificate"
            doLast {
                CertificateExtension certificate = project.extensions.getByType(CertificateExtension)

                if( !certificate.keyFile ) {
                    certificate.keyFile = certFile
                }

                KeyStore ks = new X509KeyGenerator( certificate.getKeyFile(), certificate.getKeyPassword().getChars() )
                    .issuer( certificate.getCommonName(),
                            certificate.getOrganization(),
                            certificate.getOrganizationUnit(),
                            certificate.getCity(),
                            certificate.getRegion(),
                            certificate.getCountry()
                    )
                    .keySize( certificate.keySize )
                    .daysValid( certificate.daysValid )
                    .generate()
            }
        }
    }
}
