/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.fuseanalytics.gradle.x509

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'com.fuseanalytics.gradle.x509.greeting' plugin.
 */
class GradleSslCertGenPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.fuseanalytics.gradle.x509.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
